import { financeService } from './financeService.js';
import { formatCurrency, formatDate, showToast } from '../../utilities/uiUtils.js';
import { attachCardSizeControl, loadCardSize, renderCardSizeControl } from '../../utilities/cardSizeUtils.js';

export class FinanceComponent {
    constructor(state = {}) { this.state = { view: 'overview', ...state }; this.cardSize = loadCardSize('finance'); }

    render() {
        const container = document.createElement('div');
        container.className = 'finance-module-content';
        container.innerHTML = this.renderContent();
        this.attachEventListeners(container);
        return container;
    }

    renderContent() {
        if (financeService.getBalance() === 0 && !financeService.getTransactions().length && !financeService.getGoals().length) return `${this.renderInitialSetup()}${this.renderTransactionModal()}`;
        return `<div class="finance-toolbar"><div class="finance-tabs">${['overview', 'transactions', 'goals'].map(view => `<button class="finance-tab ${this.state.view === view ? 'active' : ''}" data-view="${view}">${view[0].toUpperCase() + view.slice(1)}</button>`).join('')}</div>${renderCardSizeControl(this.cardSize)}<button class="btn btn-primary add-transaction-btn">+ Add Transaction</button></div><div class="finance-view-transition">${this.state.view === 'overview' ? this.renderOverview() : ''}${this.state.view === 'transactions' ? this.renderTransactions() : ''}${this.state.view === 'goals' ? this.renderGoals() : ''}</div>${this.renderTransactionModal()}`;
    }

    renderInitialSetup() { return `<div class="finance-init"><div class="finance-init-header"><h2>💰 Finance Tracker</h2><p>Start by setting your initial balance</p></div><form class="finance-init-form"><div class="form-group"><label for="initial-balance">Initial Balance</label><div class="input-group"><span class="currency-symbol">$</span><input type="number" id="initial-balance" min="0" step="0.01" required></div></div><button class="btn btn-primary btn-block">Set Balance</button></form></div>`; }

    renderOverview() {
        const stats = financeService.getStatistics();
        const goals = financeService.getGoals().slice(0, 2);
        const transactions = financeService.getTransactions().slice(0, 5);
        return `<div class="finance-balance"><div class="balance-label">Current Balance</div><div class="balance-amount">${formatCurrency(financeService.getBalance())}</div></div><div class="finance-stats-grid"><div class="stat-item"><div class="stat-icon income">📈</div><div class="stat-value">${formatCurrency(stats.totalIncome)}</div><div class="stat-label">Income</div></div><div class="stat-item"><div class="stat-icon expense">📉</div><div class="stat-value">${formatCurrency(stats.totalExpenses)}</div><div class="stat-label">Expenses</div></div><div class="stat-item"><div class="stat-icon">✓</div><div class="stat-value">${formatCurrency(stats.netChange)}</div><div class="stat-label">Net</div></div></div>${goals.length ? `<section class="finance-section"><h3>Goals</h3>${goals.map(goal => this.renderGoal(goal)).join('')}</section>` : ''}<section class="finance-section"><h3>Recent Transactions</h3>${transactions.length ? `<div class="transactions-list">${transactions.map(t => this.renderTransaction(t)).join('')}</div>` : '<div class="finance-empty">No transactions yet.</div>'}</section>`;
    }

    renderTransactions() { return `<section class="finance-section"><h3>All Transactions</h3><div class="transactions-list">${financeService.getTransactions().map(t => this.renderTransaction(t)).join('') || '<div class="finance-empty">No transactions yet.</div>'}</div></section>`; }
    renderGoals() { return `<section class="finance-section"><div class="section-heading"><h3>Savings Goals</h3><button class="btn btn-primary add-goal-btn">+ Add Goal</button></div><div class="goal-form-wrap hidden"><form class="goal-form"><div class="form-group"><label>Name</label><input name="name" required></div><div class="form-group"><label>Target amount</label><input name="targetAmount" type="number" min="0.01" step="0.01" required></div><div class="form-group"><label>Description</label><input name="description"></div><button class="btn btn-primary">Create Goal</button></form></div>${financeService.getGoals().map(goal => this.renderGoal(goal, true)).join('') || '<div class="finance-empty">Set a target to track progress.</div>'}</section>`; }
    renderGoal(goal, deletable = false) { const progress = financeService.getGoalProgress(goal.id); return `<div class="goal-item" data-id="${goal.id}"><div class="goal-header"><strong>${this.escape(goal.name)}</strong><strong>${Math.round(progress)}%</strong></div><div class="progress-track"><div class="progress-fill" style="width:${progress}%"></div></div><div class="goal-footer">${formatCurrency(financeService.getBalance())} of ${formatCurrency(goal.targetAmount)}${deletable ? '<button class="btn-icon delete-goal-btn">🗑️</button>' : ''}</div></div>`; }
    renderTransactionModal(transaction = null) { return `<div class="modal modal-add-transaction hidden"><div class="modal-content"><div class="modal-header"><h2>${transaction ? 'Edit Transaction' : 'Add Transaction'}</h2><button class="modal-close" type="button">×</button></div><form class="add-transaction-form" data-edit-id="${transaction?.id || ''}"><div class="form-group"><label>Type</label><div class="button-group"><label class="radio-button"><input type="radio" name="type" value="expense" ${transaction?.type !== 'income' ? 'checked' : ''}><span>Expense</span></label><label class="radio-button"><input type="radio" name="type" value="income" ${transaction?.type === 'income' ? 'checked' : ''}><span>Income</span></label></div></div><div class="form-group"><label>Amount</label><input name="amount" type="number" value="${transaction?.amount || ''}" step="0.01" min="0" required></div><div class="form-group"><label>Category</label><select name="category">${financeService.getCategories().map(cat => `<option value="${cat.id}" ${cat.id === transaction?.category ? 'selected' : ''}>${cat.icon} ${cat.name}</option>`).join('')}</select></div><div class="form-group"><label>Description</label><input name="note" value="${this.escape(transaction?.note || '')}"></div><div class="form-group"><label>Date</label><input name="date" type="date" value="${transaction?.date?.slice(0, 10) || new Date().toISOString().slice(0, 10)}"></div><button class="btn btn-primary btn-block">${transaction ? 'Save Changes' : 'Add Transaction'}</button></form></div></div>`; }
    renderTransaction(transaction) { const category = financeService.getCategory(transaction.category); return `<div class="transaction-item ${transaction.type}" data-id="${transaction.id}"><div class="transaction-icon">${category?.icon || '💳'}</div><div class="transaction-info"><div class="transaction-category">${this.escape(category?.name || 'Uncategorized')}</div><div class="transaction-note">${this.escape(transaction.note || 'No description')}</div></div><div class="transaction-amount"><span>${transaction.type === 'income' ? '+' : '-'}${formatCurrency(transaction.amount)}</span><div class="transaction-date">${formatDate(transaction.date, 'short')}</div></div><div class="transaction-actions"><button class="btn-icon edit-btn" aria-label="Edit description">✏️</button><button class="btn-icon delete-btn" aria-label="Delete">🗑️</button></div></div>`; }

    attachEventListeners(container) {
        attachCardSizeControl(container, 'finance', this.cardSize, size => { this.cardSize = size; });
        container.querySelector('.finance-init-form')?.addEventListener('submit', e => { e.preventDefault(); financeService.setInitialBalance(parseFloat(container.querySelector('#initial-balance').value) || 0); this.rerender(container); });
        container.querySelectorAll('.finance-tab').forEach(button => button.addEventListener('click', () => this.rerender(container, button.dataset.view)));
        container.querySelector('.add-transaction-btn')?.addEventListener('click', () => this.showModal(container));
        container.querySelector('.add-transaction-form')?.addEventListener('submit', e => this.saveTransaction(e, container));
        container.querySelector('.modal-close')?.addEventListener('click', () => this.hideModal(container));
        container.querySelectorAll('.edit-btn').forEach(button => button.addEventListener('click', e => { const item = e.target.closest('.transaction-item'); const transaction = financeService.getTransactions().find(t => t.id === item.dataset.id); container.querySelector('.modal-add-transaction').outerHTML = this.renderTransactionModal(transaction); this.attachEventListeners(container); this.showModal(container); }));
        container.querySelectorAll('.delete-btn').forEach(button => button.addEventListener('click', e => { if (confirm('Delete this transaction?')) { financeService.removeTransaction(e.target.closest('.transaction-item').dataset.id); this.rerender(container); } }));
        container.querySelector('.add-goal-btn')?.addEventListener('click', () => container.querySelector('.goal-form-wrap').classList.remove('hidden'));
        container.querySelector('.goal-form')?.addEventListener('submit', e => { e.preventDefault(); const data = new FormData(e.target); financeService.createGoal({ name: data.get('name'), targetAmount: parseFloat(data.get('targetAmount')), description: data.get('description') }); showToast('Goal created', 'success'); this.rerender(container, 'goals'); });
        container.querySelectorAll('.delete-goal-btn').forEach(button => button.addEventListener('click', e => { if (confirm('Delete this goal?')) { financeService.removeGoal(e.target.closest('.goal-item').dataset.id); this.rerender(container, 'goals'); } }));
    }
    saveTransaction(e, container) { e.preventDefault(); const data = new FormData(e.target); const transaction = { type: data.get('type'), amount: parseFloat(data.get('amount')), category: data.get('category'), note: data.get('note'), date: new Date(`${data.get('date')}T12:00:00`).toISOString() }; if (!transaction.amount || transaction.amount <= 0) return showToast('Amount must be greater than 0', 'error'); if (e.target.dataset.editId) { financeService.updateTransaction(e.target.dataset.editId, transaction); showToast('Transaction updated', 'success'); } else { financeService.addTransaction(transaction); showToast('Transaction added', 'success'); } this.hideModal(container); this.rerender(container); }
    rerender(container, view = this.state.view) { this.state.view = view; container.innerHTML = this.renderContent(); this.attachEventListeners(container); }
    showModal(container) { const modal = container.querySelector('.modal-add-transaction'); modal.classList.remove('hidden'); requestAnimationFrame(() => modal.classList.add('show')); }
    hideModal(container) { const modal = container.querySelector('.modal-add-transaction'); if (!modal) return; modal.classList.add('closing'); setTimeout(() => { modal.classList.remove('show', 'closing'); modal.classList.add('hidden'); }, 220); }
    escape(value) { return String(value).replace(/[&<>'"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c])); }
}
